name: Frank
#dafault_datasource_name: devdb
spring:
  datasource:
    dev1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/devdb?serverTimezone=UTC
      username: root
      password: 813552168
    dev2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/devdb2?serverTimezone=UTC
      username: root
      password: 813552168

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/devdb?serverTimezone=UTC
#    username: root
#    password: 813552168
#    driver-class-name: com.mysql.cj.jdbc.Driver
